### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by tsg-l** [prometheus/pushgateway#403]
When attempting to install the pushgateway with the following command, I get the below KeyError.

nano-prom --rpchost ::1 --rpc_port 55000 --datapath /NanoBeta/NanoBeta:/root --push_gateway http://localhost:9091 --hostname nanobeta

loaded config,  None
Traceback (most recent call last):
  File "/usr/local/bin/nano-prom", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/nano_prom_exporter/__main__.py", line 70, in main
    stats = statsCollection.gatherStats(rpcLatency)
  File "/usr/local/lib/python3.8/dist-packages/nano_prom_exporter/nanoRPC.py", line 106, in gatherStats
    stats = nanoStats(self.lastData)
  File "/usr/local/lib/python3.8/dist-packages/nano_prom_exporter/nanoRPC.py", line 26, in __init__
    self.ActiveDifficulty = collection['active_difficulty']['multiplier']
KeyError: 'active_difficulty'

**Comment by beorn7** [comment]
This doesn't seem to have anything to do with installing the Pushgateway. The error comes from (I guess) https://github.com/nanocurrency/nano_prom_exporter , so I propose to use their support channels to get help.

In different news, we use GitHub issues for bugs and (uncontroversial) feature requests. Please refer to https://prometheus.io/community/ if you need support using the Pushgateway.
