### ISSUE TITLE
Why writeQueueCapacity is only 1000?

### ISSUE THREAD

**Issue by SecretSun** [prometheus/pushgateway#476]
## Bug Report
* Why writeQueueCapacity is only 1000?
```
const (
	pushMetricName       = "push_time_seconds"
	pushMetricHelp       = "Last Unix time when changing this group in the Pushgateway succeeded."
	pushFailedMetricName = "push_failure_time_seconds"
	pushFailedMetricHelp = "Last Unix time when changing this group in the Pushgateway failed."
	writeQueueCapacity   = 1000
)
```

* System information:

		Linux 3.10.0-1127.19.1.el7.x86_64 x86_64

* Go version:

		1.18.2

* Pushgateway version:

		1.4.3

* Pushgateway command line:

		./pushgateway --log.level=debug --persistence.interval=3m --web.listen-address="0.0.0.0:9091" --web.external-url="/pushgateway"

* Logs:
```
goroutine 318427 [chan send, 1 minutes]:
github.com/prometheus/pushgateway/storage.(*DiskMetricStore).SubmitWriteRequest(0x7f9349b13ec0?, {0xc018da5230, {0xc0a2d9738090d170, 0xfc24060a86, 0xfeffc0}, 0xc018da5290, 0x1, 0xc018d1fb60})
    /Users/secret.sun/go/secret/pushgateway/storage/diskmetricstore.go:113 +0x79
github.com/prometheus/pushgateway/handler.Push.func1({0x7f9349af3e38, 0xc018d39680}, 0xc018d98a00)
    /Users/secret.sun/go/secret/pushgateway/handler/push.go:127 +0xdbb
net/http.HandlerFunc.ServeHTTP(0xc6e620?, {0x7f9349af3e38?, 0xc018d39680?}, 0xd?)
    /usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1({0xc6e620?, 0xc018d34b60?}, 0xc018d98a00)
    /Users/secret.sun/go/pkg/mod/github.com/prometheus/client_golang@v1.12.2/prometheus/promhttp/instrument_server.go:117 +0xaa
net/http.HandlerFunc.ServeHTTP(0x0?, {0xc6e620?, 0xc018d34b60?}, 0xc018da51d0?)
    /usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2({0xc6e620, 0xc018d34b60}, 0xc018d98a00)
    /Users/secret.sun/go/pkg/mod/github.com/prometheus/client_golang@v1.12.2/prometheus/promhttp/instrument_server.go:84 +0xbf
net/http.HandlerFunc.ServeHTTP(0xc0063de820?, {0xc6e620?, 0xc018d34b60?}, 0x90?)
    /usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerRequestSize.func2({0xc6e620?, 0xc018d34b60?}, 0xc018d98a00)
    /Users/secret.sun/go/pkg/mod/github.com/prometheus/client_golang@v1.12.2/prometheus/promhttp/instrument_server.go:204 +0x71
net/http.HandlerFunc.ServeHTTP(...)
    /usr/local/go/src/net/http/server.go:2084
github.com/prometheus/pushgateway/handler.Push.func2({0xc6e620?, 0xc018d34b60?}, 0xc018d9b3b0?)
    /Users/secret.sun/go/secret/pushgateway/handler/push.go:163 +0x82
github.com/prometheus/common/route.(*Router).handle.func1({0xc6e620, 0xc018d34b60}, 0xc018d5bc00, {0xc018da8740, 0x2, 0xc018da8700?})
    /Users/secret.sun/go/pkg/mod/github.com/prometheus/common@v0.34.0/route/route.go:83 +0x2ae
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc0002861e0, {0xc6e620, 0xc018d34b60}, 0xc018d5bc00)
    /Users/secret.sun/go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387 +0x82b
github.com/prometheus/common/route.(*Router).ServeHTTP(0x7f93480f3b68?, {0xc6e620?, 0xc018d34b60?}, 0xc018db6200?)
    /Users/secret.sun/go/pkg/mod/github.com/prometheus/common@v0.34.0/route/route.go:126 +0x26
net/http.(*ServeMux).ServeHTTP(0x0?, {0xc6e620, 0xc018d34b60}, 0xc018d5bc00)
    /usr/local/go/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc6d640?}, {0xc6e620, 0xc018d34b60}, 0xc018d5bc00)
    /usr/local/go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc018d3cb40, {0xc6ed30, 0xc000280330})
    /usr/local/go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:3071 +0x4db
```

**Comment by beorn7** [comment]
This value is certainly just a ballpark number to give _some_ buffering, but not too much to require too much memory.

If you have any evidence that a lower or higher number is generally better, then please let me know.

In general, I would assume in the situation where your goroutine dump is from, the storage cannot keep up with the throughput of write requests, and even more buffering wouldn't help.

Note that the Pushgateway is designed for small numbers of metrics (hundreds, or perhaps thousands at most). Many users report problems of all kinds if they try to push a large amount of metrics to the Pushgateway (mostly because they try to use the Pushgateway to turn Prometheus into a push-based monitoring system, which it is not).

**Comment by SecretSun** [comment]
Thank you so much
