### ISSUE TITLE
cloning + making + running = not working

### ISSUE THREAD

**Issue by jebl01** [prometheus/pushgateway#69]
> Note! complete golang noob speaking...

Perhaps there is something more to it, but in that case I think that the readme needs some work :-)

I can make and run, but the result is not pretty and the logs are being filled with logs like the one below:
```
2016/01/13 16:07:53 http: panic serving [::1]:51642: runtime error: invalid memory address or nil pointer dereference
goroutine 102 [running]:
net/http.(*conn).serve.func1(0xc82049e2c0, 0xe00000, 0xc82049c020)
	/usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/elazarl/go-bindata-assetfs.(*AssetFS).Open(0xc8203b7500, 0xc820450035, 0x13, 0x0, 0x0, 0x0, 0x0)
	/Users/jesblo/dev/gopath/src/github.com/prometheus/pushgateway/.build/gopath/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:148 +0x22e
net/http.serveFile(0xba4758, 0xc820030000, 0xc8204d4000, 0xb64ce0, 0xc8203b7500, 0xc820450034, 0x14, 0x1)
	/usr/local/go/src/net/http/fs.go:359 +0x158
net/http.(*fileHandler).ServeHTTP(0xc82034b3b0, 0xba4758, 0xc820030000, 0xc8204d4000)
	/usr/local/go/src/net/http/fs.go:483 +0x19c
net/http.(Handler).ServeHTTP-fm(0xba4758, 0xc820030000, 0xc8204d4000)
	/Users/jesblo/dev/gopath/src/github.com/prometheus/pushgateway/.build/gopath/src/github.com/prometheus/client_golang/prometheus/http.go:61 +0x50
github.com/prometheus/client_golang/prometheus.InstrumentHandlerFuncWithOpts.func1(0xba4680, 0xc8201f2000, 0xc8204d4000)
	/Users/jesblo/dev/gopath/src/github.com/prometheus/pushgateway/.build/gopath/src/github.com/prometheus/client_golang/prometheus/http.go:158 +0x335
net/http.HandlerFunc.ServeHTTP(0xc820273e00, 0xba4680, 0xc8201f2000, 0xc8204d4000)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/julienschmidt/httprouter.(*Router).Handler.func1(0xba4680, 0xc8201f2000, 0xc8204d4000, 0xc82000e220, 0x1, 0x1)
	/Users/jesblo/dev/gopath/src/github.com/prometheus/pushgateway/.build/gopath/src/github.com/julienschmidt/httprouter/router.go:237 +0x50
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc820011c80, 0xba4680, 0xc8201f2000, 0xc8204d4000)
	/Users/jesblo/dev/gopath/src/github.com/prometheus/pushgateway/.build/gopath/src/github.com/julienschmidt/httprouter/router.go:299 +0x193
net/http.serverHandler.ServeHTTP(0xc82001bec0, 0xba4680, 0xc8201f2000, 0xc8204d4000)
	/usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc82049e2c0)
	/usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6
```

If I run ```godep save -r ./...``` and then make, everything seems to work as expected though... Is this expected?

**Comment by beorn7** [comment]
Probably a change with the upstream dependencies (and Pushgateway is not vendored yet, see https://github.com/prometheus/pushgateway/issues/29 . I'm currently investigating. (Could already reporduce.)
